// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gadpime {
    
    
    public partial class prova {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button button2;
        
        private Gtk.Arrow arrow1;
        
        private Gtk.ColorButton colorbutton1;
    }
}
