// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gadpime {
    
    
    public partial class ClientWindow {
        
        private Gtk.Action ArchivoAction;
        
        private Gtk.Action SalirAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table1;
        
        private Gtk.Entry EntryClientName;
        
        private Gtk.Entry EntryClientSurname1;
        
        private Gtk.Entry EntryClientSurname2;
        
        private Gtk.Label LabelClientName;
        
        private Gtk.Label LabelClientSurname1;
        
        private Gtk.Label LabelClientSurname2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button button63;
        
        private Gtk.Button button48;
        
        private Gtk.Button button1;
        
        private Gtk.Button ButtonClientSave;
        
        private Gtk.Button ButtonClientClose;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget gadpime.ClientWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.ArchivoAction = new Gtk.Action("ArchivoAction", Mono.Unix.Catalog.GetString("Archivo"), null, null);
            this.ArchivoAction.ShortLabel = Mono.Unix.Catalog.GetString("Archivo");
            w2.Add(this.ArchivoAction, null);
            this.SalirAction = new Gtk.Action("SalirAction", Mono.Unix.Catalog.GetString("Salir"), null, null);
            this.SalirAction.ShortLabel = Mono.Unix.Catalog.GetString("Salir");
            w2.Add(this.SalirAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "gadpime.ClientWindow";
            this.Title = Mono.Unix.Catalog.GetString("ClientWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(2));
            // Container child gadpime.ClientWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='ArchivoAction'><menu action='SalirAction'/></menu><menu><menuitem/><menuitem/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.EntryClientName = new Gtk.Entry();
            this.EntryClientName.CanFocus = true;
            this.EntryClientName.Name = "EntryClientName";
            this.EntryClientName.IsEditable = true;
            this.EntryClientName.InvisibleChar = '●';
            this.table1.Add(this.EntryClientName);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.EntryClientName]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.EntryClientSurname1 = new Gtk.Entry();
            this.EntryClientSurname1.CanFocus = true;
            this.EntryClientSurname1.Name = "EntryClientSurname1";
            this.EntryClientSurname1.IsEditable = true;
            this.EntryClientSurname1.InvisibleChar = '●';
            this.table1.Add(this.EntryClientSurname1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.EntryClientSurname1]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.EntryClientSurname2 = new Gtk.Entry();
            this.EntryClientSurname2.CanFocus = true;
            this.EntryClientSurname2.Name = "EntryClientSurname2";
            this.EntryClientSurname2.IsEditable = true;
            this.EntryClientSurname2.InvisibleChar = '●';
            this.table1.Add(this.EntryClientSurname2);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.EntryClientSurname2]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.LabelClientName = new Gtk.Label();
            this.LabelClientName.Name = "LabelClientName";
            this.LabelClientName.LabelProp = Mono.Unix.Catalog.GetString("Nom");
            this.table1.Add(this.LabelClientName);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.LabelClientName]));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.LabelClientSurname1 = new Gtk.Label();
            this.LabelClientSurname1.Name = "LabelClientSurname1";
            this.LabelClientSurname1.LabelProp = Mono.Unix.Catalog.GetString("Cognom1");
            this.table1.Add(this.LabelClientSurname1);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.LabelClientSurname1]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.LabelClientSurname2 = new Gtk.Label();
            this.LabelClientSurname2.Name = "LabelClientSurname2";
            this.LabelClientSurname2.LabelProp = Mono.Unix.Catalog.GetString("Cognom2");
            this.table1.Add(this.LabelClientSurname2);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.LabelClientSurname2]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button63 = new Gtk.Button();
            this.button63.CanFocus = true;
            this.button63.Name = "button63";
            this.button63.UseStock = true;
            this.button63.UseUnderline = true;
            this.button63.Label = "gtk-go-back";
            this.hbox3.Add(this.button63);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.button63]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button48 = new Gtk.Button();
            this.button48.CanFocus = true;
            this.button48.Name = "button48";
            this.button48.UseStock = true;
            this.button48.UseUnderline = true;
            this.button48.Label = "gtk-go-forward";
            this.hbox3.Add(this.button48);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox3[this.button48]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseStock = true;
            this.button1.UseUnderline = true;
            this.button1.Label = "gtk-delete";
            this.hbox3.Add(this.button1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox3[this.button1]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.ButtonClientSave = new Gtk.Button();
            this.ButtonClientSave.CanFocus = true;
            this.ButtonClientSave.Name = "ButtonClientSave";
            this.ButtonClientSave.UseStock = true;
            this.ButtonClientSave.UseUnderline = true;
            this.ButtonClientSave.Label = "gtk-save";
            this.hbox3.Add(this.ButtonClientSave);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox3[this.ButtonClientSave]));
            w14.Position = 3;
            w14.Expand = false;
            w14.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.ButtonClientClose = new Gtk.Button();
            this.ButtonClientClose.CanFocus = true;
            this.ButtonClientClose.Name = "ButtonClientClose";
            this.ButtonClientClose.UseStock = true;
            this.ButtonClientClose.UseUnderline = true;
            this.ButtonClientClose.Label = "gtk-close";
            this.hbox3.Add(this.ButtonClientClose);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox3[this.ButtonClientClose]));
            w15.Position = 4;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            this.vbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 406;
            this.DefaultHeight = 226;
            this.Show();
            this.SalirAction.Activated += new System.EventHandler(this.Close);
            this.EntryClientSurname2.Changed += new System.EventHandler(this.ClientDataChanged);
            this.EntryClientSurname1.Changed += new System.EventHandler(this.ClientDataChanged);
            this.EntryClientName.Changed += new System.EventHandler(this.ClientDataChanged);
            this.button63.Clicked += new System.EventHandler(this.ClientBack);
            this.button48.Clicked += new System.EventHandler(this.ClientForward);
            this.button1.Clicked += new System.EventHandler(this.ClientDelete);
            this.ButtonClientSave.Clicked += new System.EventHandler(this.ClientSave);
            this.ButtonClientClose.Clicked += new System.EventHandler(this.Close);
        }
    }
}
